name: streamcart
version: "1.0.0"
config-version: 2

profile: streamcart

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  streamcart:
    staging:
      +materialized: view

    dimensions:
      +materialized: table

    facts:
      +materialized: incremental
      +unique_key: surrogate_key

    aggregates:
      +materialized: incremental
      +unique_key: surrogate_key
